- cluster/gce/win1803/install-ssh.psm1
> Disable password authentication in open-ssh

- hack/run-e2e.sh
> Add a script to run e2e tests

- hack/run-e2e.sh
> Properly set the LINUX_NODE_COUNT

- hack/run-e2e.sh
> Fix path in run-e2e.sh

- hack/run-e2e.sh
> run-e2e.sh: print the command executed

- hack/run-e2e.sh
> run-e2e.sh: disable log dump

- hack/run-e2e.sh
> run-e2e.sh: Fix the artifacts directory

- cluster/gce/win1803/k8s-node-setup.psm1
> Adjust kubelet flags

- cluster/gce/win1803/k8s-node-setup.psm1
> Enable kubelet's debug handlers

- cluster/gce/win1803/install-ssh.psm1
> Fix ssh keys writing

- cluster/gce/util.sh
> Add a firewall rule to allow rdp connections for debugging

- cluster/gce/util.sh
- cluster/log-dump/log-dump.sh
> Duplicate detect-node-names for linux nodes

- cluster/gce/util.sh
- cluster/gce/win1803/configure.ps1
- cluster/gce/win1803/install-ssh.psm1
- cluster/gce/win1803/k8s-node-setup.psm1
- cluster/log-dump/log-dump.sh
> Set up authorized_keys files on Windows nodes.

- cluster/log-dump/log-dump.sh
> Retry copying logs from windows nodes

- cluster/gce/win1803/install-ssh.psm1
> Allow getting ssh keys from both sshKeys and ssh-keys

- cluster/log-dump/log-dump.sh
> Get docker logs from windows nodes

- cluster/gce/win1803/configure.ps1
- cluster/gce/win1803/node-helper.sh
- cluster/gce/win1803/prepull-images.psm1
- hack/run-e2e.sh
> Prepull e2e test images

- hack/run-e2e.sh
The file has been renamed from repo-list.txt to repo-list
> Fix the repo-list file name

- cluster/common.sh
- cluster/gce/util.sh
- cluster/gce/win1803/k8s-node-setup.psm1
- cluster/get-kube-binaries.sh
- cluster/get-kube.sh
Reverts pjh/kubernetes#36
Oops...I wanted to test more before merging this. Sorry for not making it clear.
> Revert "Set and use kubernetes node binaries tar"

- cluster/gce/win1803/configure.ps1
- cluster/gce/win1803/install-ssh.psm1
- cluster/gce/win1803/k8s-node-setup.psm1
- cluster/gce/win1803/node-helper.sh
- cluster/gce/win1803/prepull-images.psm1
- cluster/gce/win1803/smoke-test.sh
Tested: smoke-test passes, still able to SSH to Windows nodes.
CC @yujuhong @mtaufen. Let me know if you have any objections to submitting this PR today. It will likely cause merge conflicts if you have pending changes, sorry for the trouble!
> Style changes for PowerShell scripts.

- cluster/common.sh
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
**Which issue(s) this PR fixes**:
Fixes #
**Does this PR introduce a user-facing change?**:
```release-note
```
> Do not look for windows node tar when USE_RELEASE_NODE_BINARIES is set

- cluster/gce/util.sh
- cluster/gce/win1803/node-helper.sh
Using newer kubelet/kube-proxy binaries for testing
> Bump the default version 1.13.2

- cluster/gce/win1803/configure.ps1
- cluster/gce/win1803/k8s-node-setup.psm1
> Clean up k8s-node-setup.psm1 and add comments for all functions.

- cluster/common.sh
- cluster/gce/util.sh
- cluster/gce/win1803/configure.ps1
- cluster/gce/win1803/k8s-node-setup.psm1
This worked and passed the smoke test just before I rebased, and after rebase the cluster won't come up.
It's failing verify-release-tars with the message "Cannot find kubernetes-node-windows-amd64.tar.gz"
I'll try to debug tomorrow.
> Run kubelet and kube-proxy as services

- cluster/gce/util.sh
- cluster/gce/win1803/configure.ps1
- cluster/gce/win1803/k8s-node-setup.psm1
Coalesces common Linux + Windows kubelet flags, moves almost all kubelet
flag generation to util.sh instead of on the node, and removes some
flags that are unused on Windows nodes.
> Improve Windows kubelet flag handling.

- README-GCE-Windows-kube-up.md
- cluster/gce/config-default.sh
- cluster/gce/config-test.sh
- cluster/gce/util.sh
- cluster/gce/win1803/smoke-test.sh
- Separate LINUX_NODE_LABELS from WINDOWS_NODE_LABELS.
- Coalesce common Linux+Windows node labels.
Includes a couple other small cleanups too.
> Improve node label handling.

- cluster/gce/win1803/install-logging-agent.psm1
> Add comment about Stackdriver flake

- cluster/gce/win1803/smoke-test.sh
> Add toleration to yet another test pod

- cluster/gce/windows/configure.ps1
This is for investigating https://github.com/kubernetes/kubernetes/issues/75148.
> Install NTFS driver in POC clusters

- cluster/gce/windows/configure.ps1
This is to try to work around https://github.com/kubernetes/kubernetes/issues/76666.
>  Force Docker version to 18.09.3

- cluster/gce/util.sh
Attempting to work around https://github.com/kubernetes/kubernetes/issues/76666#issuecomment-483896399.
> Pin Windows node image to 1809 v20190312.

- cluster/gce/windows/configure.ps1
This is for investigating issue 76666.
> Install HCS fix
